import { mountIntroSplash } from './intro-splash.js';
import { getDailyMotivationalPhrase } from './data/motivational-phrases.js';
import { exercises } from './data/exercises.js';
import { exerciseMuscleMap, exerciseVisual } from './exercise-visuals.js';

const STORAGE_KEY = 'fit-prime-data-v1';
const app = document.querySelector('#app');
const routines = [
  { id: 'upper', name: 'Upper — Fuerza', focus: 'Pecho · Espalda · Hombro', duration: '60–70 min', days: [1, 4], exercises: [
    { name: 'Press banca con barra', sets: 4, reps: 6, weight: 82.5, rest: '2:00' },
    { name: 'Remo con barra', sets: 4, reps: 8, weight: 70, rest: '2:00' },
    { name: 'Press militar', sets: 3, reps: 8, weight: 42.5, rest: '1:30' },
    { name: 'Elevaciones laterales', sets: 3, reps: 12, weight: 10, rest: '1:00' }
  ]},
  { id: 'lower', name: 'Lower — Volumen', focus: 'Pierna · Core', duration: '65–75 min', days: [2, 6], exercises: [
    { name: 'Sentadilla con barra', sets: 4, reps: 6, weight: 100, rest: '2:30' },
    { name: 'Peso muerto rumano', sets: 3, reps: 10, weight: 80, rest: '2:00' },
    { name: 'Prensa de piernas', sets: 3, reps: 12, weight: 160, rest: '1:30' },
    { name: 'Plancha', sets: 3, reps: 45, weight: 0, rest: '1:00', unit: 's' }
  ]}
];

const icons = {
  home: '<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/></svg>', chart: '<svg viewBox="0 0 24 24"><path d="M4 20V10m6 10V4m6 16v-7m6 7V7"/></svg>', dumbbell: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8.5 9v6m7-6v6M8.5 12h7M5.5 7v10m13-10v10M3.5 8.5v7m17-7v7"/></svg>', calendar: '<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4M3 10h18"/></svg>', user: '<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-4 3.2-6 8-6s7.2 2 8 6"/></svg>', plus: '<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>', arrow: '<svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>', fire: '<svg viewBox="0 0 24 24"><path d="M12 22c4 0 7-2.7 7-6.7 0-4.5-4.2-7.4-5.5-11.3C10.4 6.2 6 10 6 15.3 6 19.3 8.5 22 12 22Z"/></svg>', clock: '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>', check: '<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>', trash: '<svg viewBox="0 0 24 24"><path d="M4 7h16M10 11v6m4-6v6M9 7l1-3h4l1 3m-9 0 1 13h10l1-13"/></svg>'
};

const createDefaultData = () => ({ profile: null, sessions: [], activeSession: null, routines: JSON.parse(JSON.stringify(routines)) });
let data = load();
const exerciseCategories = [
  { id: 'all', label: 'Todos' }, { id: 'chest', label: 'Pecho' }, { id: 'back', label: 'Espalda' }, { id: 'legs', label: 'Piernas' }, { id: 'shoulders', label: 'Hombros' }, { id: 'biceps', label: 'Bíceps' }, { id: 'triceps', label: 'Tríceps' }, { id: 'core', label: 'Core' }, { id: 'cardio', label: 'Cardio y funcional' }
];
const categoryIds = { Pecho: 'chest', Espalda: 'back', Piernas: 'legs', Hombros: 'shoulders', Bíceps: 'biceps', Tríceps: 'triceps', Core: 'core', 'Cardio y funcional': 'cardio' };
let state = { page: 'inicio', modal: data.profile ? null : 'profile', mediaId: null, toast: '', exerciseFilter: 'all', exerciseSearch: '', historyMonth: { year: new Date().getFullYear(), month: new Date().getMonth() }, pendingSession: null, confirmation: null };

function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return { ...createDefaultData(), ...saved, routines: saved?.routines || createDefaultData().routines }; } catch { return createDefaultData(); } }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
function routineList() { return data.routines || []; }
function icon(name) { return `<span class="icon">${icons[name]}</span>`; }
function categoryId(exercise) { return categoryIds[exercise.category] || 'all'; }
function localDate(date = new Date()) { return new Intl.DateTimeFormat('en-CA', { timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone }).format(date); }
function dateLabel(date = new Date()) { return new Intl.DateTimeFormat('es-ES', { weekday: 'long', day: 'numeric', month: 'long' }).format(date).toLocaleUpperCase('es-ES'); }
function dateShort(date) { return new Intl.DateTimeFormat('es-ES', { day: 'numeric', month: 'short' }).format(new Date(`${date}T12:00:00`)); }
function greeting() { const h = new Date().getHours(); return h < 12 ? 'Buenos días' : h < 20 ? 'Buenas tardes' : 'Buenas noches'; }
function initials() { return (data.profile?.name || 'FP').split(' ').map(x => x[0]).slice(0, 2).join('').toUpperCase(); }
function nextRoutine() { const list = routineList(); const today = new Date().getDay() || 7; for (let i = 0; i < 7; i++) { const day = ((today - 1 + i) % 7) + 1; const routine = list.find(x => x.days?.includes(day)); if (routine) return { routine, offset: i, day }; } return { routine: list[0], offset: 0, day: today }; }
function weekDates() { const now = new Date(); const start = new Date(now); start.setDate(now.getDate() - ((now.getDay() + 6) % 7)); return Array.from({ length: 7 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); return localDate(d); }); }
function stats() { const dates = weekDates(); const sessions = data.sessions.filter(x => dates.includes(x.date)); const volume = sessions.reduce((n, x) => n + x.volume, 0); const seconds = sessions.reduce((n, x) => n + x.duration, 0); const completedSets = sessions.reduce((n, x) => n + (x.completed || 0), 0); return { sessions, volume, seconds, completedSets, byDay: dates.map(date => sessions.filter(x => x.date === date).reduce((n, x) => n + x.volume, 0)) }; }
function totalVolume(sessions = data.sessions) { return sessions.reduce((sum, session) => sum + (session.volume || 0), 0); }
function volumeLastWeek() { const start = new Date(); start.setDate(start.getDate() - ((start.getDay() + 6) % 7) - 7); const dates = Array.from({ length: 7 }, (_, index) => { const day = new Date(start); day.setDate(start.getDate() + index); return localDate(day); }); return totalVolume(data.sessions.filter(x => dates.includes(x.date))); }
function volumeLabel(volume) { if (!volume) return '0 kg'; if (volume >= 10000) return `${new Intl.NumberFormat('es-ES', { maximumFractionDigits: 1 }).format(volume / 1000)}k kg`; return `${num(volume)} kg`; }
function latestSession() { return data.sessions.slice().sort((a, b) => (b.finishedAt || 0) - (a.finishedAt || 0))[0]; }
function bestSession() { return data.sessions.reduce((best, session) => !best || session.volume > best.volume ? session : best, null); }
function muscleTotals() { const totals = {}; data.sessions.forEach(session => session.exerciseData?.forEach(exercise => { const volume = exercise.sets?.filter(set => set.completed).reduce((sum, set) => sum + set.weight * set.reps, 0) || 0; exercise.muscleGroups?.forEach(muscle => totals[muscle] = (totals[muscle] || 0) + volume); })); return Object.entries(totals).sort((a, b) => b[1] - a[1]).slice(0, 4); }
function streak() { const seen = new Set(data.sessions.map(x => x.date)); let day = new Date(); if (!seen.has(localDate(day))) day.setDate(day.getDate() - 1); let count = 0; while (seen.has(localDate(day))) { count++; day.setDate(day.getDate() - 1); } return count; }
function num(n) { return new Intl.NumberFormat('es-ES', { maximumFractionDigits: 0 }).format(n); }
function duration(seconds) { const m = Math.round(seconds / 60); return m >= 60 ? `${Math.floor(m / 60)}h ${m % 60 ? `${m % 60}m` : ''}` : `${m} min`; }
function liveDuration(seconds) { const h = Math.floor(seconds / 3600), m = Math.floor(seconds % 3600 / 60), s = seconds % 60; return h ? `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}` : `${m}:${String(s).padStart(2, '0')}`; }
function restToSeconds(rest) { const [m, s] = String(rest || '1:30').split(':').map(Number); return (m || 0) * 60 + (s || 0); }
function exerciseFor(name) { const normalized = name?.toLocaleLowerCase('es').trim(); const aliases = { 'press banca con barra': 'press-banca', 'press de banca': 'press-banca' }; return exercises.find(x => x.id === aliases[normalized] || x.name.toLocaleLowerCase('es') === normalized); }
function sessionSet(weight, reps) { return { id: crypto.randomUUID(), weight: Number(weight) || 0, reps: Math.max(0, Number.parseInt(reps, 10) || 0), completed: false, completedAt: null }; }
function createSessionExercises(routine) { return routine.exercises.map((exercise, index) => { const catalog = exerciseFor(exercise.name); return { id: crypto.randomUUID(), exerciseId: catalog?.id || exercise.name, name: exercise.name, order: index, restSeconds: restToSeconds(exercise.rest), targetSets: exercise.sets, targetReps: exercise.reps, muscleGroups: catalog?.primaryMuscles || [], notes: '', supersetId: null, sets: Array.from({ length: exercise.sets }, () => sessionSet(exercise.weight, exercise.reps)) }; }); }
function activeStats(active = data.activeSession) { const sets = active?.exercises?.flatMap(x => x.sets) || []; const completed = sets.filter(x => x.completed); return { total: sets.length, completed: completed.length, volume: completed.reduce((sum, set) => sum + set.weight * set.reps, 0) }; }
function restRemaining(timer) { if (!timer) return 0; if (timer.paused) return timer.remaining; return Math.max(0, timer.durationSeconds - Math.floor((Date.now() - timer.startedAt) / 1000)); }
function empty(message) { return `<div class="empty-state"><span>${icon('dumbbell')}</span><p>${message}</p></div>`; }
function logo() { return '<div class="brand"><img src="/icons/fit-prime-logo.png" alt="Fit Prime" /><span>FIT<span>PRIME</span></span></div>'; }
function nav() { const items = [['inicio','home','Inicio'],['progreso','chart','Progreso'],['entrenar','dumbbell','Entrenar'],['perfil','user','Perfil']]; return `<nav>${items.map(([id, i, label]) => `<button class="nav-item ${state.page === id ? 'active' : ''}" data-page="${id}">${icon(i)}<span>${label}</span></button>`).join('')}</nav>`; }
function avatarMarkup(className = '') { return data.profile?.profileImage ? `<img class="${className}" src="${data.profile.profileImage}" alt="Foto de perfil de ${data.profile.name}" />` : initials(); }
function miniSession() { const active = data.activeSession; if (!active || state.page === 'sesion') return ''; const currentExercise = active.exercises.find(exercise => !exercise.sets.every(set => set.completed)) || active.exercises[0]; const elapsed = Math.max(0, Math.round((Date.now() - active.startedAt) / 1000)); return `<aside class="mini-session" aria-label="Entrenamiento en curso"><button class="mini-session__resume" data-resume-session aria-label="Volver al entrenamiento"><span class="mini-session__dot" aria-hidden="true"></span><span><b>${active.routineName}</b><small>${currentExercise?.name || 'Añade ejercicios para empezar'} · <time data-mini-session-duration>${liveDuration(elapsed)}</time></small></span></button><button class="mini-session__finish" data-finish-session aria-label="Finalizar entrenamiento">${icon('check')}</button><button class="mini-session__discard" data-discard-session aria-label="Descartar entrenamiento">${icon('trash')}</button></aside>`; }
function shell(content) { return `<main class="phone-shell"><header>${logo()}<button class="avatar" data-page="perfil" aria-label="Abrir perfil">${avatarMarkup()}</button></header>${content}${miniSession()}${state.page !== 'sesion' ? nav() : ''}</main>`; }
function stat(iconName, value, label) { return `<div class="stat-card">${icon(iconName)}<strong>${value}</strong><small>${label}</small></div>`; }

function home() { const s = stats(), next = nextRoutine(), current = localDate(), max = Math.max(...s.byDay, 1), st = streak(); return shell(`
  <section class="greeting"><p data-today>${dateLabel()}</p><h1>${greeting()}, <em>${data.profile?.name || 'atleta'}.</em></h1><span>${getDailyMotivationalPhrase()}</span></section>
  <section class="hero-card"><div><span class="eyebrow">RACHA ACTUAL</span><h2>${st} ${st === 1 ? 'día' : 'días'} <i>en forma</i></h2><p>${st ? 'Sigue así: cada sesión cuenta.' : 'Completa tu primer entrenamiento para iniciar tu racha.'}</p></div><div class="ring"><b>${st}</b><small>días</small></div></section>
  <section class="section-head"><h2>Tu próximo entrenamiento</h2><button data-page="entrenar">Ver plan ${icon('arrow')}</button></section>
  ${next.routine ? `<section class="next-workout"><div class="workout-art"><span>${next.routine.id.toUpperCase()}</span></div><div><p class="eyebrow">${next.offset ? `EN ${next.offset} DÍA${next.offset > 1 ? 'S' : ''}` : 'HOY'} · 18:30</p><h2>${next.routine.name}</h2><p>${next.routine.exercises.length} ejercicios · ${next.routine.duration}</p><button class="text-button" data-start-routine="${next.routine.id}">Comenzar sesión ${icon('arrow')}</button></div></section>` : `<section class="empty-state"><p>Crea una rutina o empieza un entrenamiento vacío.</p><button class="text-button" data-page="entrenar">Ir a Entrenar ${icon('arrow')}</button></section>`}
  <section class="section-head"><h2>Esta semana</h2><button data-page="progreso">Detalles ${icon('arrow')}</button></section>
  <div class="stats-grid">${stat('dumbbell', `${s.sessions.length} / 4`, 'sesiones')}${stat('fire', `${num(s.volume / 1000)}k`, 'volumen kg')}${stat('clock', duration(s.seconds), 'tiempo activo')}</div>
  <section class="week-chart home-weekly-volume"><div class="chart-top"><div><span class="eyebrow">VOLUMEN SEMANAL</span><h2>${num(s.volume)} <small>kg</small></h2></div><span class="positive">${s.sessions.length ? `${s.sessions.length} sesiones` : 'Sin sesiones'}</span></div><div class="bars">${s.byDay.map((v, i) => `<div class="bar-col"><i class="${weekDates()[i] === current ? 'today' : ''}" style="height:${v ? Math.max(16, Math.round(v / max * 100)) : 7}%"></i><span>${['L','M','X','J','V','S','D'][i]}</span></div>`).join('')}</div></section>
`); }

function progress() { const weekly = stats(), total = totalVolume(), previous = volumeLastWeek(), last = latestSession(), best = bestSession(), muscles = muscleTotals(), max = Math.max(...weekly.byDay, 1), comparison = previous ? Math.round((weekly.volume - previous) / previous * 100) : null; return shell(`
  <section class="page-title progress-title"><p class="eyebrow">ANÁLISIS REAL</p><h1>Tu <em>progreso</em></h1><span>Basado en tus sesiones finalizadas.</span></section>
  <section class="metric-main progress-total"><div><span class="eyebrow">VOLUMEN TOTAL</span><h2>${volumeLabel(total)}</h2><p class="${comparison !== null && comparison >= 0 ? 'positive' : ''}">${data.sessions.length ? comparison === null ? `${data.sessions.length} sesiones registradas` : `${comparison >= 0 ? '↑' : '↓'} ${Math.abs(comparison)}% vs. semana anterior` : 'Aún no hay actividad'}</p></div><div class="line-chart"><svg viewBox="0 0 240 96" preserveAspectRatio="none"><path d="M0 82 ${weekly.byDay.map((value, index) => `L${index * 40} ${88 - Math.min(80, value ? value / max * 80 : 0)}`).join(' ')}" fill="none" stroke="#dfff4f" stroke-width="3"/></svg></div></section>
  <section class="section-head spaced"><h2>Esta semana</h2><span class="section-caption">Lun — Dom</span></section>
  <div class="stats-grid progress-stats">${stat('dumbbell', weekly.sessions.length, 'sesiones')}${stat('fire', volumeLabel(weekly.volume).replace(' kg', ''), 'volumen kg')}${stat('clock', duration(weekly.seconds), 'tiempo activo')}</div>
  ${!data.sessions.length ? `<section class="progress-empty">${empty('Cuando termines un entrenamiento, tus métricas aparecerán aquí.')}<button class="primary" data-page="entrenar">${icon('dumbbell')} Empezar entrenamiento</button></section>` : `
    <section class="progress-panel"><div class="chart-top"><div><span class="eyebrow">VOLUMEN SEMANAL</span><h2>${volumeLabel(weekly.volume)}</h2></div><span class="positive">${weekly.completedSets} series</span></div><div class="bars weekly-bars">${weekly.byDay.map((value, index) => `<div class="bar-col"><i class="${weekDates()[index] === localDate() ? 'today' : ''}" style="height:${value ? Math.max(9, Math.round(value / max * 100)) : 4}%"></i><span>${['L','M','X','J','V','S','D'][index]}</span></div>`).join('')}</div></section>
    <section class="analysis-grid"><article><span>ÚLTIMO ENTRENAMIENTO</span><b>${last.name}</b><p>${dateShort(last.date)} · ${duration(last.duration)} · ${volumeLabel(last.volume)}</p></article><article><span>MEJOR SESIÓN</span><b>${best.name}</b><p>${volumeLabel(best.volume)} · ${dateShort(best.date)}</p></article></section>
    <section class="section-head spaced"><h2>Músculos más trabajados</h2></section><section class="muscles progress-muscles">${muscles.map(([muscle, volume]) => `<div><span>${muscle}</span><i><b style="width:${Math.round(volume / Math.max(muscles[0]?.[1] || 1, 1) * 100)}%"></b></i><strong>${volumeLabel(volume)}</strong></div>`).join('')}</section>
    <section class="section-head spaced"><h2>Últimas sesiones</h2></section><div class="workout-list">${data.sessions.slice().sort((a,b) => (b.finishedAt || 0) - (a.finishedAt || 0)).slice(0, 3).map(sessionRow).join('')}</div>
  `}
  ${historyContent()}
`); }

function training() { const list = routineList(), next = nextRoutine(); return shell(`
  <section class="page-title training-title"><p class="eyebrow">TU BIBLIOTECA</p><h1>Entrena <em>hoy</em></h1><span>Elige una rutina o crea tu propia sesión.</span></section>
  <button class="empty-workout" data-empty-workout>${icon('plus')} <span><b>Empezar entrenamiento vacío</b><small>Añade ejercicios sobre la marcha</small></span>${icon('arrow')}</button>
  <section class="section-head"><h2>Rutinas</h2><button data-new-routine>Nueva ${icon('plus')}</button></section>
  <div class="training-actions"><button data-new-routine>${icon('calendar')}<span>Nueva rutina</span></button><button data-page="explorar">${icon('chart')}<span>Explorar ejercicios</span></button></div>
  <section class="section-head compact"><h2>Mis rutinas <span>(${list.length})</span></h2></section>
  <section class="routine-library">${list.length ? list.map(routine => { const demo = routine.exercises.map(exercise => exerciseFor(exercise.name)).find(exercise => exercise?.videoUrl); return `<article class="library-card ${routine.id === next.routine?.id ? 'recommended' : ''}"><div class="library-head"><div><p class="eyebrow">${routine.id === next.routine?.id ? 'PRÓXIMA SESIÓN' : 'RUTINA ACTIVA'}</p><h2>${routine.name}</h2></div><button aria-label="Opciones de ${routine.name}" data-routine-menu="${routine.id}">•••</button></div><p>${routine.exercises.map(x => x.name).join(' · ')}</p>${demo ? `<button class="technique-link routine-technique" data-exercise="${demo.id}">Ver técnica de ${demo.name}</button>` : ''}<div class="library-footer"><span>${routine.exercises.length} ejercicios · ${routine.duration || '60 min aprox.'}</span><button class="primary" data-start-routine="${routine.id}">Empezar rutina</button></div></article>`; }).join('') : `<div class="empty-state"><p>No tienes rutinas creadas todavía.</p><button class="text-button" data-new-routine>Crear rutina ${icon('arrow')}</button></div>`}</section>
`); }

function filteredExercises() { const term = state.exerciseSearch.trim().toLocaleLowerCase('es'); return exercises.filter(exercise => (state.exerciseFilter === 'all' || categoryId(exercise) === state.exerciseFilter) && (!term || `${exercise.name} ${exercise.category} ${exercise.primaryMuscles.join(' ')}`.toLocaleLowerCase('es').includes(term))); }
function explore() { const visible = filteredExercises(); return shell(`
  <section class="page-title training-title"><p class="eyebrow">BIBLIOTECA</p><h1>Explora <em>ejercicios</em></h1><span>${exercises.length} movimientos con técnica y músculos trabajados.</span></section>
  <div class="exercise-search"><input data-exercise-search value="${state.exerciseSearch}" placeholder="Buscar ejercicio" aria-label="Buscar ejercicio" />${icon('chart')}</div>
  <div class="exercise-filters">${exerciseCategories.map(category => `<button class="${state.exerciseFilter === category.id ? 'selected' : ''}" data-filter="${category.id}" aria-pressed="${state.exerciseFilter === category.id}">${category.label}</button>`).join('')}</div>
  <section class="exercise-catalog">${visible.length ? visible.map(exerciseCard).join('') : `<div class="exercise-empty"><p>${state.exerciseSearch ? 'No se encontraron ejercicios con estos filtros.' : 'No hay ejercicios en esta categoría.'}</p><button data-clear-exercise-filters>Limpiar filtros</button></div>`}</section>
`); }

function exerciseCard(exercise) { return `<article class="exercise-card" data-category="${categoryId(exercise)}"><button class="exercise-card__media" type="button" data-media-open="${exercise.id}" aria-label="Ampliar imagen de ${exercise.name}">${exerciseVisual(exercise, { compact: true, alt: exercise.name })}<span class="media-expand-badge" aria-hidden="true">⌕</span></button><button class="exercise-card__content" type="button" ${state.pickerMode ? `data-add-session-exercise="${exercise.id}"` : `data-exercise="${exercise.id}"`}><span><small>${exercise.category.toUpperCase()} · ${exercise.level}</small><b>${exercise.name}</b><em>${exercise.primaryMuscles.join(' · ')}</em></span>${state.pickerMode ? icon('plus') : icon('arrow')}</button></article>`; }

function session() { const active = data.activeSession; if (!active?.exercises) { state.page = 'entrenar'; return training(); } const elapsed = Math.max(0, Math.round((Date.now() - active.startedAt) / 1000)), summary = activeStats(active), timer = active.restTimer, remaining = restRemaining(timer); return shell(`
  <section class="session-top"><button class="back-button" data-page="entrenar" aria-label="Volver">‹</button><div><p class="eyebrow">SESIÓN EN CURSO</p><h1>${active.routineName}</h1></div></section>
  <section class="live-summary"><div><span>Duración</span><b data-session-duration>${liveDuration(elapsed)}</b></div><div><span>Volumen</span><b>${num(summary.volume)} <small>kg</small></b></div><div><span>Series</span><b>${summary.completed}<small> / ${summary.total}</small></b></div></section>
  ${timer ? `<section class="rest-timer ${remaining === 0 ? 'complete' : ''}" data-rest-timer><span class="eyebrow" data-rest-label>${remaining ? 'DESCANSO EN CURSO' : 'DESCANSO COMPLETADO'}</span><b data-rest-remaining>${liveDuration(remaining)}</b><div><button data-rest-action="${timer.paused ? 'resume' : 'pause'}">${timer.paused ? 'Reanudar' : 'Pausar'}</button><button data-rest-action="minus">−15 s</button><button data-rest-action="plus">+15 s</button><button data-rest-action="skip">Saltar</button></div></section>` : ''}
  <section class="live-exercises">${active.exercises.length ? active.exercises.map((exercise, index) => sessionExercise(exercise, index)).join('') : `<div class="empty-state session-empty"><p>Añade ejercicios para comenzar tu entrenamiento.</p><button class="primary session-empty__action" data-open-session-picker aria-label="Añadir ejercicio al entrenamiento">Añadir ejercicio</button></div>`}</section>
  <section class="session-actions">${active.exercises.length ? `<button class="primary" data-open-session-picker>${icon('plus')} Añadir ejercicio</button>` : ''}<div><button class="secondary session-action-button" data-session-settings>Configuración</button><button class="secondary session-action-button danger-action" data-discard-session>Descartar entrenamiento</button></div></section>
  <button class="primary finish-button" data-finish-session>${icon('check')} Finalizar sesión</button>
`); }

function sessionExercise(exercise, index) { const previousSession = data.sessions.slice().reverse().find(x => x.routineId === data.activeSession.routineId); const last = previousSession?.exerciseData?.find(x => x.exerciseId === exercise.exerciseId); const previous = last ? `${last.sets.filter(s => s.completed).map(s => `${s.weight} kg × ${s.reps}`).join(' · ') || 'Sin series completadas'} · ${dateShort(previousSession.date)}` : 'Sin datos anteriores'; return `<article class="live-exercise ${exercise.supersetId ? 'in-superset' : ''}"><div class="exercise-title"><div><span class="eyebrow">${exercise.supersetId ? `SUPERSERIE ${exercise.supersetId} · ` : ''}0${index + 1}</span><h2>${exercise.name}</h2><button class="technique-link" data-exercise="${exercise.exerciseId}">Ver técnica</button></div><button class="exercise-menu" data-exercise-menu="${exercise.id}" aria-label="Opciones de ${exercise.name}">•••</button></div><p class="previous-set">Última vez: ${previous}</p><div class="rest-control"><span>Descanso: <b>${liveDuration(exercise.restSeconds)}</b></span><select data-rest-select="${exercise.id}" aria-label="Descanso para ${exercise.name}">${[30,45,60,90,120,180].map(x => `<option value="${x}" ${x === exercise.restSeconds ? 'selected' : ''}>${liveDuration(x)}</option>`).join('')}</select></div><div class="set-table"><div class="set-header"><span>Serie</span><span>Kg</span><span>Reps</span><span></span></div>${exercise.sets.map((set, setIndex) => `<div class="set-row ${set.completed ? 'done' : ''}"><b>${setIndex + 1}</b><input type="number" min="0" step="0.5" value="${set.weight}" data-set-field="weight" data-exercise-id="${exercise.id}" data-set-id="${set.id}" aria-label="Peso serie ${setIndex + 1}" /><input type="number" min="0" step="1" value="${set.reps}" data-set-field="reps" data-exercise-id="${exercise.id}" data-set-id="${set.id}" aria-label="Repeticiones serie ${setIndex + 1}" /><button data-toggle-set="${exercise.id}:${set.id}" aria-label="Completar serie ${setIndex + 1}">${set.completed ? '✓' : '○'}</button></div>`).join('')}</div><button class="add-set" data-add-set="${exercise.id}">${icon('plus')} Añadir serie</button></article>`; }

function sessionDate(session) { return session.finishedAt || session.startedAt ? new Date(session.finishedAt || session.startedAt) : new Date(`${session.date}T12:00:00`); }
function monthLabel(year, month, options = { month: 'long', year: 'numeric' }) { return new Intl.DateTimeFormat('es-ES', options).format(new Date(year, month, 1)); }
function availableHistoryMonths() { const keys = new Set(data.sessions.map(session => { const date = sessionDate(session); return `${date.getFullYear()}-${date.getMonth()}`; })); const now = new Date(); Array.from({ length: 12 }, (_, index) => { const date = new Date(now.getFullYear(), now.getMonth() - index, 1); keys.add(`${date.getFullYear()}-${date.getMonth()}`); }); return [...keys].map(key => { const [year, month] = key.split('-').map(Number); return { year, month }; }).sort((a, b) => b.year - a.year || b.month - a.month); }
function sessionRow(s) { const date = sessionDate(s); return `<button class="workout-row" data-session-id="${s.id}"><div class="workout-symbol lime">${icon('dumbbell')}</div><div><small>${dateShort(localDate(date)).toUpperCase()}</small><h3>${s.name}</h3><p>${duration(s.duration)} · ${s.exercises} ejercicios</p></div><strong>${num(s.volume)} kg${icon('arrow')}</strong></button>`; }
function historyContent() { const selected = state.historyMonth, sessions = data.sessions.filter(session => { const date = sessionDate(session); return date.getFullYear() === selected.year && date.getMonth() === selected.month; }), volume = sessions.reduce((sum, session) => sum + (session.volume || 0), 0), seconds = sessions.reduce((sum, session) => sum + (session.duration || 0), 0), monthName = monthLabel(selected.year, selected.month); return `
  <section class="progress-history">
  <section class="section-head spaced"><div><p class="eyebrow">TU ACTIVIDAD</p><h2>Historial de sesiones</h2></div><button class="period" data-history-month-picker aria-haspopup="dialog">${monthName}⌄</button></section>
  <section class="calendar"><div class="calendar-head"><b>${monthName.toUpperCase()}</b><span>${sessions.length} ${sessions.length === 1 ? 'sesión' : 'sesiones'}</span></div><div class="days-label">${['L','M','X','J','V','S','D'].map(x => `<span>${x}</span>`).join('')}</div><div class="date-grid">${Array.from({ length: new Date(selected.year, selected.month + 1, 0).getDate() }, (_, i) => { const d = new Date(selected.year, selected.month, i + 1); const key = localDate(d); return `<button class="${sessions.some(session => localDate(sessionDate(session)) === key) ? 'trained' : ''} ${key === localDate() ? 'current' : ''}">${i + 1}</button>`; }).join('')}</div></section>
  <div class="history-metrics"><span>${volumeLabel(volume)} volumen</span><span>${duration(seconds)} activo</span></div>
  <section class="section-head"><h2>Sesiones completadas</h2></section><section class="workout-list">${sessions.length ? sessions.slice().sort((a, b) => sessionDate(b) - sessionDate(a)).map(sessionRow).join('') : `<div class="empty-state"><p>No hay sesiones en este mes.</p><small>Completa un entrenamiento para que aparezca aquí.</small><button class="text-button" data-page="entrenar">Ir a Entrenar ${icon('arrow')}</button></div>`}</section>
  </section>`; }
function history() { return shell(`<section class="page-title"><p class="eyebrow">TU ACTIVIDAD</p><h1>Historial de <em>sesiones</em></h1></section>${historyContent()}`); }

function profile() { const p = data.profile || {}, last = latestSession(), totalSeconds = data.sessions.reduce((sum, x) => sum + (x.duration || 0), 0); return shell(`
  <section class="profile-hero"><button class="large-avatar" data-avatar-upload aria-label="Cambiar foto de perfil">${avatarMarkup('avatar-image')}</button><div><p class="eyebrow">TU PERFIL</p><h1>${p.name || 'Tu perfil'}</h1><span>${p.goal || 'Define tu objetivo'}</span></div></section>
  <div class="profile-photo-actions"><button data-avatar-upload>${data.profile?.profileImage ? 'Cambiar foto' : 'Añadir foto'}</button>${data.profile?.profileImage ? '<button data-remove-avatar>Eliminar foto</button>' : ''}<input type="file" accept="image/jpeg,image/png,image/webp" data-avatar-input hidden /></div>
  <div class="profile-stats"><div><b>${data.sessions.length}</b><span>sesiones</span></div><div><b>${streak()}</b><span>días racha</span></div><div><b>${volumeLabel(totalVolume()).replace(' kg', '')}</b><span>volumen</span></div></div>
  <section class="section-head"><h2>Datos personales</h2><button data-modal="profile">Editar ${icon('arrow')}</button></section>
  <div class="profile-data"><div><span>Edad</span><b>${p.age || '—'} años</b></div><div><span>Peso</span><b>${p.weight || '—'} kg</b></div><div><span>Altura</span><b>${p.height || '—'} cm</b></div></div>
  <section class="profile-insight">${last ? `<span>ÚLTIMO ENTRENAMIENTO</span><b>${last.name}</b><p>${dateShort(last.date)} · ${duration(last.duration)} · ${volumeLabel(last.volume)}</p>` : `<span>EMPIEZA A ENTRENAR</span><b>Aún no hay sesiones</b><p>Completa tu primer entrenamiento para ver tus estadísticas.</p>`}<small>${duration(totalSeconds)} de tiempo total</small></section>
  <section class="section-head"><h2>Preferencias</h2></section><div class="settings"><button data-modal="profile">${icon('user')} Editar datos personales <i>›</i></button><button data-reset>${icon('calendar')} Reiniciar datos locales <i>›</i></button></div>
`); }

function profileModal() { const p = data.profile || {}; return `<div class="overlay"><form class="bottom-sheet form-sheet" data-profile-form><button class="close" type="button" data-close>×</button><span class="eyebrow">${data.profile ? 'EDITAR PERFIL' : 'BIENVENIDO A FIT PRIME'}</span><h2>${data.profile ? 'Tus datos personales' : 'Empecemos por conocerte.'}</h2><p>Usaremos estos datos solo para personalizar tu experiencia.</p><label>Nombre<input name="name" value="${p.name || ''}" required maxlength="40" placeholder="Tu nombre" /></label><div class="form-grid"><label>Edad<input name="age" type="number" min="15" max="100" value="${p.age || ''}" required /></label><label>Peso (kg)<input name="weight" type="number" min="30" max="300" step="0.1" value="${p.weight || ''}" required /></label></div><label>Altura (cm)<input name="height" type="number" min="130" max="230" value="${p.height || ''}" required /></label><label>Objetivo principal<select name="goal" required><option value="">Selecciona un objetivo</option>${['Ganar músculo','Perder grasa','Mantenerse en forma','Fuerza','Resistencia','Otro'].map(x => `<option ${p.goal === x ? 'selected' : ''}>${x}</option>`).join('')}</select></label><p class="form-error" data-form-error></p><button class="primary" type="submit">Guardar datos</button>${data.profile ? '<button class="secondary" type="button" data-close>Cancelar</button>' : ''}</form></div>`; }
function routineModal(id = '') { const routine = routineList().find(item => item.id === id); const selected = new Set(routine?.exercises.map(item => item.exerciseId || exerciseFor(item.name)?.id).filter(Boolean)); const first = routine?.exercises[0] || {}; const groups = ['Personalizada', 'Pecho', 'Espalda', 'Piernas', 'Hombros', 'Brazos', 'Core', 'Full body']; return `<div class="overlay"><form class="bottom-sheet form-sheet routine-form" data-routine-form data-routine-id="${routine?.id || ''}"><button class="close" type="button" data-close>×</button><span class="eyebrow">${routine ? 'EDITAR RUTINA' : 'NUEVA RUTINA'}</span><h2>${routine ? 'Ajusta tu rutina' : 'Crea tu rutina'}</h2><label>Nombre<input name="name" required maxlength="50" value="${routine?.name || ''}" placeholder="Ej. Pecho y tríceps" /></label><label>Grupo<select name="group">${groups.map(group => `<option ${routine?.group === group ? 'selected' : ''}>${group}</option>`).join('')}</select></label><label>Descripción <small>Opcional</small><input name="focus" maxlength="90" value="${routine?.focus || ''}" placeholder="Ej. Pecho · tríceps · hombro" /></label><div class="form-grid"><label>Series<input name="sets" type="number" min="1" max="10" value="${first.sets || 3}" /></label><label>Reps<input name="reps" type="number" min="1" max="50" value="${first.reps || 10}" /></label></div><p class="eyebrow routine-picker-label">EJERCICIOS</p><div class="routine-picker">${exercises.map(x => `<label><input type="checkbox" name="exercise" value="${x.id}" ${selected.has(x.id) ? 'checked' : ''}><span>${x.name}<small>${x.category}</small></span></label>`).join('')}</div><p class="form-error" data-routine-error></p><button class="primary" type="submit">${routine ? 'Guardar cambios' : 'Guardar rutina'}</button><button class="secondary" type="button" data-close>Cancelar</button></form></div>`; }
function routineMenu(id) { const routine = routineList().find(item => item.id === id); if (!routine) return ''; return `<div class="overlay"><section class="bottom-sheet action-sheet"><button class="close" data-close>×</button><span class="eyebrow">RUTINA</span><h2>${routine.name}</h2><button data-edit-routine="${id}">Editar rutina</button><button data-duplicate-routine="${id}">Duplicar rutina</button><button class="danger" data-delete-routine="${id}">Eliminar rutina</button></section></div>`; }
function historyMonthModal() { const selected = state.historyMonth; return `<div class="overlay" data-history-month-overlay><section class="bottom-sheet action-sheet history-month-sheet"><button class="close" data-close aria-label="Cerrar selector de mes">×</button><span class="eyebrow">FILTRAR HISTORIAL</span><h2>Selecciona un mes</h2>${availableHistoryMonths().map(item => `<button class="${item.year === selected.year && item.month === selected.month ? 'selected' : ''}" data-history-month="${item.year}-${item.month}">${monthLabel(item.year, item.month)}${item.year === selected.year && item.month === selected.month ? icon('check') : ''}</button>`).join('')}</section></div>`; }
function activeSessionModal() { const active = data.activeSession; return `<div class="overlay"><section class="bottom-sheet active-session-sheet"><button class="close" data-close aria-label="Cerrar">×</button><span class="eyebrow">ENTRENAMIENTO EN CURSO</span><h2>Ya tienes una sesión activa</h2><p>${active?.routineName || 'Tu entrenamiento'} sigue guardado en este dispositivo.</p><button class="primary" data-resume-session>Reanudar entrenamiento</button><button class="secondary danger-action" data-discard-and-start>Descartar y empezar nuevo</button><button class="secondary" data-close>Cancelar</button></section></div>`; }
function confirmationDialog() { const dialog = state.confirmation; if (!dialog) return ''; return `<div class="overlay"><section class="bottom-sheet confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><span class="eyebrow">CONFIRMACIÓN</span><h2 id="confirm-title">${dialog.title}</h2><p>${dialog.message}</p><div class="confirm-dialog__actions"><button class="secondary" data-confirm-cancel>${dialog.cancelText || 'Cancelar'}</button><button class="primary ${dialog.danger ? 'danger-confirm' : ''}" data-confirm-accept>${dialog.confirmText || 'Confirmar'}</button></div></section></div>`; }
function sessionSettingsModal() { const active = data.activeSession; return `<div class="overlay"><form class="bottom-sheet form-sheet" data-session-settings-form><button class="close" type="button" data-close>×</button><span class="eyebrow">CONFIGURACIÓN</span><h2>Ajustes del entrenamiento</h2><label>Nombre del entrenamiento<input name="name" maxlength="60" value="${active?.routineName || ''}" required /></label><label>Descanso por defecto<select name="rest">${[30,45,60,90,120,180].map(seconds => `<option value="${seconds}" ${active?.exercises[0]?.restSeconds === seconds ? 'selected' : ''}>${liveDuration(seconds)}</option>`).join('')}</select></label><p>El descanso se aplicará a los ejercicios actuales.</p><button class="primary" type="submit">Guardar cambios</button><button class="secondary" type="button" data-close>Cancelar</button></form></div>`; }
function exerciseMediaFrame(exercise, mode = 'preview') {
  if (mode === 'viewer' && exercise.videoUrl) return `<video src="${exercise.videoUrl}" ${exercise.imageUrl ? `poster="${exercise.imageUrl}"` : ''} controls autoplay muted loop playsinline preload="metadata">Tu navegador no puede reproducir este vídeo.</video>`;
  if (exercise.imageUrl) return `<img src="${exercise.imageUrl}" alt="${exercise.videoAlt || `Demostración de ${exercise.name}`}" loading="${mode === 'viewer' ? 'eager' : 'lazy'}" />`;
  return exerciseVisual(exercise, { animated: true, className: mode === 'viewer' ? 'exercise-motion--viewer' : 'exercise-motion--detail' });
}
function exerciseDetailMedia(exercise) { return `<button class="exercise-detail-media" type="button" data-media-open="${exercise.id}" aria-label="Ampliar demostración de ${exercise.name}"><span class="eyebrow">DEMOSTRACIÓN DEL MOVIMIENTO</span><span class="exercise-detail-media__frame">${exerciseMediaFrame(exercise)}</span><span class="exercise-detail-media__hint">${exercise.videoUrl ? 'Toca para ver en grande' : 'Toca para ampliar'}</span></button>`; }
function exerciseMediaViewer() { const exercise = exercises.find(x => x.id === state.mediaId); if (!exercise) return ''; return `<div class="overlay media-viewer-overlay" data-media-overlay><section class="media-viewer" role="dialog" aria-modal="true" aria-label="Visualización ampliada de ${exercise.name}"><button class="close media-viewer__close" data-media-close aria-label="Cerrar visualización">×</button><div class="media-viewer__header"><span class="eyebrow">${exercise.category.toUpperCase()} · ${exercise.level.toUpperCase()}</span><h2>${exercise.name}</h2></div><div class="media-viewer__stage">${exerciseMediaFrame(exercise, 'viewer')}</div><p>${exercise.videoAlt || exercise.description}</p></section></div>`; }
function exerciseModal(id) { const exercise = exercises.find(x => x.id === id); if (!exercise) return ''; return `<div class="overlay" data-exercise-overlay><section class="bottom-sheet exercise-sheet" data-exercise-sheet><div class="exercise-sheet__header" data-drag-handle><span class="exercise-sheet__grip" aria-hidden="true"></span><button class="close" data-exercise-close aria-label="Cerrar detalle del ejercicio">×</button></div>${exerciseDetailMedia(exercise)}<span class="eyebrow">${exercise.category.toUpperCase()} · ${exercise.level.toUpperCase()}</span><h2>${exercise.name}</h2><p>${exercise.description}</p>${exerciseMuscleMap(exercise)}<div class="muscle-tags"><b>Principal: ${exercise.primaryMuscles.join(', ')}</b><span>Secundarios: ${exercise.secondaryMuscles.join(', ')}</span></div><div class="exercise-meta"><span>${exercise.recommendedSets} series</span><span>${exercise.recommendedReps}</span><span>${exercise.recommendedRestSeconds}s descanso</span></div><h3>Cómo hacerlo</h3><ol>${exercise.steps.map(x => `<li>${x}</li>`).join('')}</ol><h3>Evita</h3><p>${exercise.commonMistakes.join(' · ')}</p><button class="primary" data-close>Entendido</button></section></div>`; }
function sessionMenu(exerciseId) { const exercise = findActiveExercise(exerciseId); return `<div class="overlay"><section class="bottom-sheet action-sheet"><button class="close" data-close>×</button><span class="eyebrow">OPCIONES DE EJERCICIO</span><h2>${exercise.name}</h2><button data-session-action="up" data-exercise-id="${exerciseId}">↑ Subir ejercicio</button><button data-session-action="down" data-exercise-id="${exerciseId}">↓ Bajar ejercicio</button><button data-session-action="superset" data-exercise-id="${exerciseId}">↗ ${exercise.supersetId ? 'Quitar de superserie' : 'Añadir a superserie'}</button><button data-session-action="replace" data-exercise-id="${exerciseId}">⇄ Reemplazar ejercicio</button><button class="danger" data-session-action="delete" data-exercise-id="${exerciseId}">Eliminar ejercicio</button></section></div>`; }
function replaceModal(exerciseId) { return `<div class="overlay"><section class="bottom-sheet replace-sheet"><button class="close" data-close>×</button><span class="eyebrow">REEMPLAZAR EJERCICIO</span><h2>Elige un sustituto</h2><div class="replace-list">${exercises.map(x => `<button data-replace-exercise="${x.id}" data-target-exercise="${exerciseId}"><span>${x.category}</span><b>${x.name}</b>${icon('arrow')}</button>`).join('')}</div></section></div>`; }
function modal() { let content = ''; if (state.confirmation) content = confirmationDialog(); else if (state.modal === 'profile') content = profileModal(); else if (state.modal === 'routine') content = routineModal(); else if (state.modal === 'history-month') content = historyMonthModal(); else if (state.modal === 'active-session') content = activeSessionModal(); else if (state.modal === 'session-settings') content = sessionSettingsModal(); else if (state.modal?.startsWith('routine:')) content = routineModal(state.modal.split(':')[1]); else if (state.modal?.startsWith('routine-menu:')) content = routineMenu(state.modal.split(':')[1]); else if (state.modal?.startsWith('exercise:')) content = exerciseModal(state.modal.split(':')[1]); else if (state.modal?.startsWith('menu:')) content = sessionMenu(state.modal.split(':')[1]); else if (state.modal?.startsWith('replace:')) content = replaceModal(state.modal.split(':')[1]); return content + exerciseMediaViewer(); }
function toast() { return state.toast ? `<div class="toast" role="status">${state.toast}</div>` : ''; }
function render() { const pages = { inicio: home, progreso: progress, entrenar: training, explorar: explore, perfil: profile, sesion: session }; app.innerHTML = (pages[state.page] || progress)() + modal() + toast(); bind(); }
function dismissExerciseModal(sheet = document.querySelector('[data-exercise-sheet]')) { if (!sheet) { state.modal = null; state.mediaId = null; render(); return; } sheet.classList.add('is-closing'); window.setTimeout(() => { state.modal = null; state.mediaId = null; render(); }, 210); }
function closeMediaViewer() { state.mediaId = null; render(); }
function goBack() { if (state.mediaId) { closeMediaViewer(); return; } if (state.modal) { if (state.modal.startsWith('exercise:')) dismissExerciseModal(); else { state.modal = null; render(); } return; } if (state.page === 'inicio') return; state.pickerMode = false; state.page = state.page === 'explorar' ? 'entrenar' : state.page === 'sesion' ? 'entrenar' : 'inicio'; render(); }
function enableEdgeSwipeBack() { let startX = 0, startY = 0, tracking = false; const isInteractive = target => target.closest('button,input,select,textarea,video,a,[contenteditable="true"],.exercise-filters'); document.addEventListener('touchstart', event => { const touch = event.touches[0]; if (!touch || touch.clientX > 28 || isInteractive(event.target)) return; startX = touch.clientX; startY = touch.clientY; tracking = true; }, { passive: true }); document.addEventListener('touchend', event => { if (!tracking) return; tracking = false; const touch = event.changedTouches[0], deltaX = touch.clientX - startX, deltaY = Math.abs(touch.clientY - startY); if (deltaX >= 90 && deltaX > deltaY) goBack(); }, { passive: true }); document.addEventListener('touchcancel', () => { tracking = false; }, { passive: true }); }

function beginRoutine(id) { const routine = routineList().find(x => x.id === id); if (!routine) return; data.activeSession = { id: crypto.randomUUID(), routineId: id, routineName: routine.name, startedAt: Date.now(), updatedAt: Date.now(), exercises: createSessionExercises(routine), restTimer: null, supersets: [] }; save(); state.pendingSession = null; state.modal = null; state.page = 'sesion'; render(); }
function beginEmptyWorkout() { data.activeSession = { id: crypto.randomUUID(), routineId: 'empty', routineName: 'Entrenamiento vacío', startedAt: Date.now(), updatedAt: Date.now(), exercises: [], restTimer: null, supersets: [] }; save(); state.pendingSession = null; state.modal = null; state.page = 'sesion'; render(); }
function requestSession(session) { if (data.activeSession) { state.pendingSession = session; state.modal = 'active-session'; render(); return; } if (session.type === 'routine') beginRoutine(session.id); else beginEmptyWorkout(); }
function startRoutine(id) { requestSession({ type: 'routine', id }); }
function startEmptyWorkout() { requestSession({ type: 'empty' }); }
function addExerciseToActive(exerciseId) { const source = exercises.find(x => x.id === exerciseId); if (!source || !data.activeSession) return; const sets = Number.parseInt(source.recommendedSets, 10) || 3, reps = Number.parseInt(source.recommendedReps, 10) || 10; data.activeSession.exercises.push({ id: crypto.randomUUID(), exerciseId: source.id, name: source.name, order: data.activeSession.exercises.length, restSeconds: source.recommendedRestSeconds || 90, targetSets: sets, targetReps: reps, muscleGroups: source.primaryMuscles, notes: '', supersetId: null, sets: Array.from({ length: sets }, () => sessionSet(0, reps)) }); updateActive(); state.pickerMode = false; state.page = 'sesion'; state.toast = `${source.name} añadido a la sesión`; render(); clearToast(); }
function askConfirmation({ title, message, confirmText = 'Confirmar', danger = false, onConfirm }) { state.confirmation = { title, message, confirmText, danger, onConfirm }; render(); }
function resolveConfirmation() { const onConfirm = state.confirmation?.onConfirm; state.confirmation = null; onConfirm?.(); }
function cancelConfirmation() { state.confirmation = null; render(); }
function completeSession() { const active = data.activeSession, summary = activeStats(active); if (!active) return; const elapsed = Math.max(60, Math.round((Date.now() - active.startedAt) / 1000)); data.sessions.push({ id: active.id, routineId: active.routineId, name: active.routineName, date: localDate(), startedAt: active.startedAt, finishedAt: Date.now(), volume: summary.volume, duration: elapsed, exercises: active.exercises.length, completed: summary.completed, exerciseData: active.exercises, supersets: active.supersets }); data.activeSession = null; save(); state.page = 'progreso'; state.toast = `Sesión guardada · ${num(summary.volume)} kg`; render(); clearToast(); }
function finishSession() { const summary = activeStats(); if (!summary.completed) { askConfirmation({ title: 'Finalizar sin series', message: 'No has completado ninguna serie. ¿Quieres guardar la sesión igualmente?', confirmText: 'Finalizar sesión', onConfirm: completeSession }); return; } completeSession(); }
function discardActiveSession() { if (!data.activeSession) return; askConfirmation({ title: 'Descartar entrenamiento', message: 'Se perderán los datos de esta sesión en curso.', confirmText: 'Descartar', danger: true, onConfirm: () => { data.activeSession = null; save(); state.modal = null; state.toast = 'Entrenamiento descartado'; render(); clearToast(); } }); }
function discardAndStartPending() { const pending = state.pendingSession; if (!pending) return; data.activeSession = null; save(); pending.type === 'routine' ? beginRoutine(pending.id) : beginEmptyWorkout(); }
function updateActive() { if (data.activeSession) { data.activeSession.updatedAt = Date.now(); save(); } }
function findActiveExercise(id) { return data.activeSession.exercises.find(x => x.id === id); }
function toggleSet(exerciseId, setId) { const exercise = findActiveExercise(exerciseId), set = exercise?.sets.find(x => x.id === setId); if (!set) return; set.completed = !set.completed; set.completedAt = set.completed ? Date.now() : null; data.activeSession.restTimer = set.completed ? { exerciseId, setId, startedAt: Date.now(), durationSeconds: exercise.restSeconds, paused: false } : null; updateActive(); state.toast = set.completed ? 'Serie completada · descanso iniciado' : 'Serie marcada como pendiente'; render(); clearToast(); }
function changeRest(action) { const timer = data.activeSession?.restTimer; if (!timer) return; const current = restRemaining(timer); if (action === 'skip') data.activeSession.restTimer = null; else if (action === 'pause') Object.assign(timer, { paused: true, remaining: current }); else if (action === 'resume') Object.assign(timer, { paused: false, startedAt: Date.now(), durationSeconds: timer.remaining }); else { const next = Math.max(0, current + (action === 'plus' ? 15 : -15)); Object.assign(timer, { paused: false, startedAt: Date.now(), durationSeconds: next }); } updateActive(); render(); }
function removeSessionExercise(exerciseId) { const active = data.activeSession, index = active?.exercises.findIndex(item => item.id === exerciseId); if (index < 0) return; active.exercises.splice(index, 1); active.exercises.forEach((item, order) => item.order = order); updateActive(); state.modal = null; state.toast = 'Ejercicio eliminado'; render(); clearToast(); }
function sessionAction(action, exerciseId) { const active = data.activeSession, index = active.exercises.findIndex(x => x.id === exerciseId), exercise = active.exercises[index]; if (action === 'up' && index > 0) [active.exercises[index - 1], active.exercises[index]] = [exercise, active.exercises[index - 1]]; if (action === 'down' && index < active.exercises.length - 1) [active.exercises[index + 1], active.exercises[index]] = [exercise, active.exercises[index + 1]]; if (action === 'superset') { exercise.supersetId = exercise.supersetId ? null : String.fromCharCode(65 + new Set(active.exercises.map(x => x.supersetId).filter(Boolean)).size); active.supersets = [...new Set(active.exercises.map(x => x.supersetId).filter(Boolean))]; } if (action === 'replace') { state.modal = `replace:${exerciseId}`; render(); return; } if (action === 'delete') { askConfirmation({ title: 'Eliminar ejercicio', message: `¿Eliminar ${exercise.name} de esta sesión?${exercise.sets.some(set => set.completed) ? ' Se perderán sus series completadas.' : ''}`, confirmText: 'Eliminar', danger: true, onConfirm: () => removeSessionExercise(exerciseId) }); return; } active.exercises.forEach((item, order) => item.order = order); updateActive(); state.modal = null; state.toast = 'Sesión actualizada'; render(); clearToast(); }
function replaceExercise(targetId, newId, confirmed = false) { const exercise = findActiveExercise(targetId), replacement = exercises.find(x => x.id === newId); if (!exercise || !replacement) return; if (!confirmed && exercise.sets.some(set => set.completed)) { askConfirmation({ title: 'Reemplazar ejercicio', message: 'Este ejercicio tiene series completadas y esos datos se perderán.', confirmText: 'Reemplazar', danger: true, onConfirm: () => replaceExercise(targetId, newId, true) }); return; } const sets = Number.parseInt(replacement.recommendedSets, 10) || 3, reps = Number.parseInt(replacement.recommendedReps, 10) || 10; Object.assign(exercise, { exerciseId: replacement.id, name: replacement.name, muscleGroups: replacement.primaryMuscles, targetSets: sets, targetReps: reps, notes: '', sets: Array.from({ length: sets }, () => sessionSet(0, reps)) }); updateActive(); state.modal = null; state.toast = 'Ejercicio reemplazado'; render(); clearToast(); }
function resizeProfileImage(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error('No se pudo leer la imagen.')); reader.onload = () => { const image = new Image(); image.onerror = () => reject(new Error('La imagen no es válida.')); image.onload = () => { const size = 512, scale = Math.max(size / image.width, size / image.height), width = Math.round(image.width * scale), height = Math.round(image.height * scale), canvas = document.createElement('canvas'); canvas.width = size; canvas.height = size; const context = canvas.getContext('2d'); context.drawImage(image, (size - width) / 2, (size - height) / 2, width, height); resolve(canvas.toDataURL('image/jpeg', .84)); }; image.src = reader.result; }; reader.readAsDataURL(file); }); }
async function setProfileImage(file) { if (!file || !['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { state.toast = 'Selecciona una imagen JPG, PNG o WebP.'; render(); clearToast(); return; } if (file.size > 8 * 1024 * 1024) { state.toast = 'La imagen debe ocupar menos de 8 MB.'; render(); clearToast(); return; } try { data.profile.profileImage = await resizeProfileImage(file); save(); state.toast = 'Foto de perfil actualizada'; render(); clearToast(); } catch (error) { state.toast = error.message; render(); clearToast(); } }
function clearToast() { window.setTimeout(() => { state.toast = ''; render(); }, 3200); }
function bind() {
  document.querySelectorAll('[data-page]').forEach(x => x.onclick = () => { state.page = x.dataset.page; state.modal = null; state.pickerMode = false; render(); });
  document.querySelectorAll('[data-modal]').forEach(x => x.onclick = () => { state.modal = x.dataset.modal; render(); });
  document.querySelectorAll('[data-close]').forEach(x => x.onclick = () => { state.modal = null; render(); });
  document.querySelectorAll('[data-confirm-cancel]').forEach(x => x.onclick = cancelConfirmation);
  document.querySelectorAll('[data-confirm-accept]').forEach(x => x.onclick = resolveConfirmation);
  document.querySelectorAll('[data-history-month-picker]').forEach(x => x.onclick = () => { state.modal = 'history-month'; render(); });
  document.querySelectorAll('[data-history-month]').forEach(x => x.onclick = () => { const [year, month] = x.dataset.historyMonth.split('-').map(Number); state.historyMonth = { year, month }; state.modal = null; render(); });
  const historyOverlay = document.querySelector('[data-history-month-overlay]'); if (historyOverlay) historyOverlay.onclick = event => { if (event.target === historyOverlay) { state.modal = null; render(); } };
  document.querySelectorAll('[data-exercise-close]').forEach(x => x.onclick = () => dismissExerciseModal());
  const exerciseSheet = document.querySelector('[data-exercise-sheet]'), exerciseOverlay = document.querySelector('[data-exercise-overlay]'); if (exerciseSheet) { let startY = 0, distance = 0, tracking = false; const isInteractive = target => target.closest('button,input,select,textarea,video,a'); exerciseSheet.addEventListener('touchstart', event => { if (exerciseSheet.scrollTop > 0 || isInteractive(event.target)) return; startY = event.touches[0].clientY; distance = 0; tracking = true; }, { passive: true }); exerciseSheet.addEventListener('touchmove', event => { if (!tracking) return; distance = Math.max(0, event.touches[0].clientY - startY); if (distance) { event.preventDefault(); exerciseSheet.style.transform = `translateY(${Math.min(distance, 180)}px)`; } }, { passive: false }); exerciseSheet.addEventListener('touchend', () => { if (!tracking) return; tracking = false; exerciseSheet.style.transform = ''; if (distance > 96) dismissExerciseModal(exerciseSheet); }, { passive: true }); }
  if (exerciseOverlay) exerciseOverlay.onclick = event => { if (event.target === exerciseOverlay) dismissExerciseModal(exerciseSheet); };
  document.querySelectorAll('[data-media-open]').forEach(x => x.onclick = () => { state.mediaId = x.dataset.mediaOpen; render(); });
  document.querySelectorAll('[data-media-close]').forEach(x => x.onclick = closeMediaViewer);
  const mediaOverlay = document.querySelector('[data-media-overlay]'); if (mediaOverlay) mediaOverlay.onclick = event => { if (event.target === mediaOverlay) closeMediaViewer(); };
  window.onkeydown = event => { if (event.key === 'Escape' && state.mediaId) closeMediaViewer(); else if (event.key === 'Escape' && state.modal) dismissExerciseModal(exerciseSheet); };
  const demoVideo = document.querySelector('[data-demo-video]'), demoToggle = document.querySelector('[data-demo-toggle]'); if (demoVideo && demoToggle) { const fallback = document.querySelector('[data-demo-fallback]'); const syncDemoButton = () => { const playing = !demoVideo.paused; demoToggle.querySelector('[data-demo-icon]').textContent = playing ? 'Ⅱ' : '▶'; demoToggle.querySelector('[data-demo-label]').textContent = playing ? 'Pausar' : 'Reproducir'; }; const showFallback = () => { fallback.hidden = false; demoToggle.hidden = true; }; demoToggle.onclick = async () => { try { if (demoVideo.paused) await demoVideo.play(); else demoVideo.pause(); syncDemoButton(); } catch { showFallback(); } }; demoVideo.onloadeddata = () => { fallback.hidden = true; demoToggle.hidden = false; }; demoVideo.onplay = syncDemoButton; demoVideo.onpause = syncDemoButton; demoVideo.onerror = showFallback; requestAnimationFrame(syncDemoButton); }
  document.querySelectorAll('[data-start-routine]').forEach(x => x.onclick = () => startRoutine(x.dataset.startRoutine));
  document.querySelectorAll('[data-exercise]').forEach(x => x.onclick = () => { state.modal = `exercise:${x.dataset.exercise}`; render(); });
  document.querySelectorAll('[data-new-routine]').forEach(x => x.onclick = () => { state.modal = 'routine'; render(); });
  document.querySelectorAll('[data-routine-menu]').forEach(x => x.onclick = () => { state.modal = `routine-menu:${x.dataset.routineMenu}`; render(); });
  document.querySelectorAll('[data-edit-routine]').forEach(x => x.onclick = () => { state.modal = `routine:${x.dataset.editRoutine}`; render(); });
  document.querySelectorAll('[data-duplicate-routine]').forEach(x => x.onclick = () => { const source = routineList().find(item => item.id === x.dataset.duplicateRoutine); if (!source) return; data.routines.push({ ...JSON.parse(JSON.stringify(source)), id: crypto.randomUUID(), name: `${source.name} (copia)`, days: [] }); save(); state.modal = null; state.toast = 'Rutina duplicada'; render(); clearToast(); });
  document.querySelectorAll('[data-delete-routine]').forEach(x => x.onclick = () => { const routine = routineList().find(item => item.id === x.dataset.deleteRoutine); if (!routine) return; askConfirmation({ title: 'Eliminar rutina', message: `¿Eliminar la rutina “${routine.name}”?`, confirmText: 'Eliminar', danger: true, onConfirm: () => { data.routines = routineList().filter(item => item.id !== routine.id); save(); state.modal = null; state.toast = 'Rutina eliminada'; render(); clearToast(); } }); });
  document.querySelectorAll('[data-empty-workout]').forEach(x => x.onclick = startEmptyWorkout);
  document.querySelectorAll('[data-open-session-picker]').forEach(x => x.onclick = () => { state.pickerMode = true; state.page = 'explorar'; render(); });
  document.querySelectorAll('[data-add-session-exercise]').forEach(x => x.onclick = () => addExerciseToActive(x.dataset.addSessionExercise));
  document.querySelectorAll('[data-resume-session]').forEach(x => x.onclick = () => { state.page = 'sesion'; render(); });
  document.querySelectorAll('[data-discard-session]').forEach(x => x.onclick = discardActiveSession);
  document.querySelectorAll('[data-discard-and-start]').forEach(x => x.onclick = discardAndStartPending);
  document.querySelectorAll('[data-session-settings]').forEach(x => x.onclick = () => { state.modal = 'session-settings'; render(); });
  document.querySelectorAll('[data-filter]').forEach(x => x.onclick = () => { state.exerciseFilter = x.dataset.filter; render(); });
  document.querySelectorAll('[data-clear-exercise-filters]').forEach(x => x.onclick = () => { state.exerciseFilter = 'all'; state.exerciseSearch = ''; render(); });
  const search = document.querySelector('[data-exercise-search]'); if (search) search.oninput = () => { state.exerciseSearch = search.value; const cursor = search.selectionStart; render(); requestAnimationFrame(() => { const input = document.querySelector('[data-exercise-search]'); input?.focus(); input?.setSelectionRange(cursor, cursor); }); };
  document.querySelectorAll('[data-toggle-set]').forEach(x => x.onclick = () => { const [exerciseId, setId] = x.dataset.toggleSet.split(':'); toggleSet(exerciseId, setId); });
  document.querySelectorAll('[data-rest-action]').forEach(x => x.onclick = () => changeRest(x.dataset.restAction));
  document.querySelectorAll('[data-set-field]').forEach(x => x.onchange = () => { const set = findActiveExercise(x.dataset.exerciseId)?.sets.find(y => y.id === x.dataset.setId); if (!set) return; set[x.dataset.setField] = x.dataset.setField === 'reps' ? Math.max(0, Number.parseInt(x.value, 10) || 0) : Math.max(0, Number(x.value) || 0); updateActive(); render(); });
  document.querySelectorAll('[data-rest-select]').forEach(x => x.onchange = () => { findActiveExercise(x.dataset.restSelect).restSeconds = Number(x.value); updateActive(); state.toast = 'Descanso actualizado'; render(); clearToast(); });
  document.querySelectorAll('[data-add-set]').forEach(x => x.onclick = () => { const exercise = findActiveExercise(x.dataset.addSet), last = exercise.sets.at(-1); exercise.sets.push(sessionSet(last?.weight, last?.reps || exercise.targetReps)); updateActive(); state.toast = 'Nueva serie añadida'; render(); clearToast(); });
  document.querySelectorAll('[data-exercise-menu]').forEach(x => x.onclick = () => { state.modal = `menu:${x.dataset.exerciseMenu}`; render(); });
  document.querySelectorAll('[data-session-action]').forEach(x => x.onclick = () => sessionAction(x.dataset.sessionAction, x.dataset.exerciseId));
  document.querySelectorAll('[data-replace-exercise]').forEach(x => x.onclick = () => replaceExercise(x.dataset.targetExercise, x.dataset.replaceExercise));
  document.querySelectorAll('[data-finish-session]').forEach(x => x.onclick = finishSession);
  document.querySelectorAll('[data-reset]').forEach(x => x.onclick = () => askConfirmation({ title: 'Reiniciar datos locales', message: 'Se eliminarán tu perfil, rutinas y entrenamientos guardados en este dispositivo.', confirmText: 'Reiniciar datos', danger: true, onConfirm: () => { localStorage.removeItem(STORAGE_KEY); data = createDefaultData(); state = { page: 'inicio', modal: 'profile', mediaId: null, toast: '', exerciseFilter: 'all', exerciseSearch: '', historyMonth: { year: new Date().getFullYear(), month: new Date().getMonth() }, pendingSession: null, confirmation: null }; render(); } }));
  document.querySelectorAll('[data-avatar-upload]').forEach(x => x.onclick = () => document.querySelector('[data-avatar-input]')?.click());
  const avatarInput = document.querySelector('[data-avatar-input]'); if (avatarInput) avatarInput.onchange = () => setProfileImage(avatarInput.files?.[0]);
  document.querySelectorAll('[data-remove-avatar]').forEach(x => x.onclick = () => { delete data.profile.profileImage; save(); state.toast = 'Foto de perfil eliminada'; render(); clearToast(); });
  const form = document.querySelector('[data-profile-form]'); if (form) form.onsubmit = event => { event.preventDefault(); const values = Object.fromEntries(new FormData(form)); const error = form.querySelector('[data-form-error]'); const age = Number(values.age), weight = Number(values.weight), height = Number(values.height); if (!values.name.trim() || !values.goal || age < 15 || age > 100 || weight < 30 || weight > 300 || height < 130 || height > 230) { error.textContent = 'Revisa los datos: edad 15–100, peso 30–300 kg y altura 130–230 cm.'; return; } data.profile = { name: values.name.trim(), age, weight, height, goal: values.goal }; save(); state.modal = null; state.toast = 'Perfil actualizado correctamente'; render(); clearToast(); };
  const routineForm = document.querySelector('[data-routine-form]'); if (routineForm) routineForm.onsubmit = event => { event.preventDefault(); const formData = new FormData(routineForm), selected = [...formData.getAll('exercise')], name = formData.get('name')?.trim(), focus = formData.get('focus')?.trim(), group = formData.get('group'), error = routineForm.querySelector('[data-routine-error]'), id = routineForm.dataset.routineId; if (!name || !selected.length) { error.textContent = 'Indica un nombre y selecciona al menos un ejercicio.'; return; } const sets = Math.max(1, Number(formData.get('sets')) || 3), reps = Math.max(1, Number(formData.get('reps')) || 10), exercisesForRoutine = selected.map(exerciseId => { const exercise = exercises.find(item => item.id === exerciseId); return { exerciseId, name: exercise.name, sets, reps, weight: 0, rest: '1:30' }; }), routine = { id: id || crypto.randomUUID(), name, group, focus, days: id ? routineList().find(item => item.id === id)?.days || [] : [], duration: `${selected.length * 12} min aprox.`, createdAt: id ? routineList().find(item => item.id === id)?.createdAt || Date.now() : Date.now(), exercises: exercisesForRoutine }; if (id) data.routines = routineList().map(item => item.id === id ? routine : item); else data.routines.push(routine); save(); state.modal = null; state.toast = id ? 'Rutina actualizada' : 'Rutina creada'; render(); clearToast(); };
  const settingsForm = document.querySelector('[data-session-settings-form]'); if (settingsForm) settingsForm.onsubmit = event => { event.preventDefault(); const values = new FormData(settingsForm), name = values.get('name')?.trim(), rest = Number(values.get('rest')); if (!name || !data.activeSession) return; data.activeSession.routineName = name; data.activeSession.exercises.forEach(exercise => exercise.restSeconds = rest); updateActive(); state.modal = null; state.toast = 'Configuración guardada'; render(); clearToast(); };
}

render();
mountIntroSplash();
enableEdgeSwipeBack();
window.setInterval(() => { if (state.page === 'inicio' && !state.modal) render(); }, 60000);
window.setInterval(() => { if (!data.activeSession) return; const elapsed = Math.round((Date.now() - data.activeSession.startedAt) / 1000); const miniDuration = document.querySelector('[data-mini-session-duration]'); if (miniDuration) miniDuration.textContent = liveDuration(elapsed); if (state.page !== 'sesion' || state.modal) return; const durationNode = document.querySelector('[data-session-duration]'); if (durationNode) durationNode.textContent = liveDuration(elapsed); const remaining = restRemaining(data.activeSession.restTimer), restNode = document.querySelector('[data-rest-remaining]'); if (restNode) { restNode.textContent = liveDuration(remaining); if (!remaining) { document.querySelector('[data-rest-timer]')?.classList.add('complete'); document.querySelector('[data-rest-label]').textContent = 'DESCANSO COMPLETADO'; } } }, 1000);
